services:
  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GRAPHQL_ENDPOINT=/graphql
    depends_on:
      - graphql

  storybook:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: storybook
    ports:
      - "6006:6006"
    environment:
      - NODE_ENV=production

  graphql:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@postgres:5432/dashboard
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  shared-network:
    external: true
