services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dashboard
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    networks:
      - internal-network

networks:
  shared-network:
    external: true
  internal-network:
    external: false
